### ISSUE TITLE
add instructions to build project myself

### ISSUE THREAD

**Issue by EtzBetz** [Vodes/XDCC-AutoDL#1]
hey there,

i like this project, the only issue i have, is, that I need the bot name to work the same way as the file name works, e.g. using containsIgnoreCase instead of equalsIgnoreCase.

i would just change up the code by myself, the problem is that it is hard to setup the environment myself, since i am not that much of a java expert.

**Comment by Vodes** [comment]
I've been just building it in my IDE until now.
I now added maven for all the dependency management and for the building process. ([debe5ac](https://github.com/Vodes/XDCC-AutoDL/commit/debe5acee389e03e419f27f874398d4bc1fd0a9d))
If stuff goes smoothly for you, feel free to close the issue.

**Comment by EtzBetz** [comment]
Great, all that works flawlessly now.
Tyvm
